version: "3.7"
services:
  redis:
    image: redis
    container_name: redis_chameleon
    restart: always
    expose:
      - 6379
  chameleon_api:
    build: .
    container_name: chameleon_api
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
