version: "3.7"
services:
  redis:
    image: redis
    container_name: redis_chameleon
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"
  chameleon_server:
    image: node:12
    container_name: chameleon_server
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379